### ISSUE TITLE
Nmap Parser Error

### ISSUE THREAD

**Issue by kdirectorate** [calebstewart/python-htb#1]
I get an exception when running "htb machine enum" with the machine "Resolute" active.

Service detection performed. Please report any incorrect results at https://nmap.org/submit/ .
Nmap done: 1 IP address (1 host up) scanned in 131.17 seconds
Traceback (most recent call last):
  File "/usr/local/bin/htb", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/htb/__main__.py", line 1299, in main
    cmd.onecmd(" ".join([shlex.quote(x) for x in sys.argv[1:]]))
  File "/usr/local/lib/python3.7/dist-packages/cmd2/cmd2.py", line 2064, in onecmd
    stop = func(statement)
  File "/usr/local/lib/python3.7/dist-packages/cmd2/decorators.py", line 223, in cmd_wrapper
    return func(cmd2_app, args)
  File "/usr/local/lib/python3.7/dist-packages/htb/__main__.py", line 246, in do_machine
    actions[args.action](args)
  File "/usr/local/lib/python3.7/dist-packages/htb/__main__.py", line 551, in _machine_enum
    args.machine.enumerate()
  File "/usr/local/lib/python3.7/dist-packages/htb/machine.py", line 455, in enumerate
    self.services.append(Service.from_nmap(s.strip()))
  File "/usr/local/lib/python3.7/dist-packages/htb/scanner/scanner.py", line 51, in from_nmap
    self.port = int(service_data[0])
ValueError: invalid literal for int() with base 10: 'Site: Default-First-Site-Name)'

[scans.zip](https://github.com/calebstewart/python-htb/files/4371888/scans.zip)

**Comment by kdirectorate** [comment]
I got the same error on "Sauna" with the same "ValueError: invalid literal for int() with base 10: 'Site: Default-First-Site-Name)'" message.

**Comment by calebstewart** [comment]
This should be fixed by commit 9edec59e1c3a04010678b5dc21ea4c371410dbfc. Let me know if it isn't fixed!

**Comment by kdirectorate** [comment]
Yes, it worked perfectly now. Thanks!
