### ISSUE TITLE
Exception while running enum4linux on "Nest"

### ISSUE THREAD

**Issue by kdirectorate** [calebstewart/python-htb#2]
```
kali@kali:~$ htb machine scan
...

|    Groups on nest.htb    |
 ========================== 

[+] Getting builtin groups:
[E] Can't get builtin groups: NT_STATUS_ACCESS_DENIED

[+] Getting builtin group memberships:

[+] Getting local groups:
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/dist-packages/htb/scanner/scanner.py", line 191, in _do_background_scan
    tracker.events.put(tracker)
AttributeError: 'NoneType' object has no attribute 'put'
```

**Comment by calebstewart** [comment]
I've been trying to track this error down with someone else too, and I can't reproduce for some reason. Did you press "C-z" to background the task?

**Comment by calebstewart** [comment]
I just pushed 4a263a0. This should fix the issue. I just tested backgrounding scans and they complete successfully on my end. I'm not sure why the issue was only showing up some of the time, but I'm 99% sure I found the culprit. If you could test again just to verify, I'd appreciate it.

**Comment by kdirectorate** [comment]
Yes, the latest update fixed this. Thanks!
